name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Download dependencies
      run: go mod download
      
    - name: Build all packages
      run: |
        # Build each main package individually
        for dir in $(find . -name "main.go" -exec dirname {} \; | sort -u); do
          echo "Building $dir"
          (cd "$dir" && go build .)
        done
        
    - name: Run vet
      run: go vet ./...
      
    - name: Run tests (only for directories with tests)
      run: |
        for dir in $(find . -name "*_test.go" -exec dirname {} \; | sort -u); do
          echo "Testing $dir"
          (cd "$dir" && go test .)
        done
